-- Setup OLIST_PROJECT database and BRONZE schema with warehouse configuration
-- Co-authored with CoCo
SHOW WAREHOUSES;
ALTER WAREHOUSE COMPUTE_WH RESUME;
CREATE DATABASE OLIST_PROJECT;
USE DATABASE OLIST_PROJECT;
CREATE SCHEMA BRONZE;
USE SCHEMA BRONZE;
SHOW WAREHOUSES;
USE WAREHOUSE COMPUTE_WH;
SHOW TABLES;

USE DATABASE OLIST_PROJECT;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

 USE SCHEMA SILVER;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(customer_id IS NULL) AS customer_id_nulls,
    COUNT_IF(customer_unique_id IS NULL) AS customer_unique_id_nulls,
    COUNT_IF(customer_zip_code_prefix IS NULL) AS customer_zip_code_prefix_nulls,
    COUNT_IF(customer_city IS NULL) AS customer_city_nulls,
    COUNT_IF(customer_state IS NULL) AS customer_state_nulls
FROM BRONZE.OLIST_CUSTOMERS;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(geolocation_zip_code_prefix IS NULL) AS geolocation_zip_code_prefix_nulls,
    COUNT_IF(geolocation_lat IS NULL) AS geolocation_lat_nulls,
    COUNT_IF(geolocation_lng IS NULL) AS geolocation_lng_nulls,
    COUNT_IF(geolocation_city IS NULL) AS geolocation_city_nulls,
    COUNT_IF(geolocation_state IS NULL) AS geolocation_state_nulls
FROM BRONZE.OLIST_GEOLOCATION;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(order_id IS NULL) AS order_id_nulls,
    COUNT_IF(customer_id IS NULL) AS customer_id_nulls,
    COUNT_IF(order_status IS NULL) AS order_status_nulls,
    COUNT_IF(order_purchase_timestamp IS NULL) AS order_purchase_timestamp_nulls,
    COUNT_IF(order_approved_at IS NULL) AS order_approved_at_nulls,
    COUNT_IF(order_delivered_carrier_date IS NULL) AS order_delivered_carrier_date_nulls,
    COUNT_IF(order_delivered_customer_date IS NULL) AS order_delivered_customer_date_nulls,
    COUNT_IF(order_estimated_delivery_date IS NULL) AS order_estimated_delivery_date_nulls
FROM BRONZE.OLIST_ORDERS;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(order_id IS NULL) AS order_id_nulls,
    COUNT_IF(order_item_id IS NULL) AS order_item_id_nulls,
    COUNT_IF(product_id IS NULL) AS product_id_nulls,
    COUNT_IF(seller_id IS NULL) AS seller_id_nulls,
    COUNT_IF(shipping_limit_date IS NULL) AS shipping_limit_date_nulls,
    COUNT_IF(price IS NULL) AS price_nulls,
    COUNT_IF(freight_value IS NULL) AS freight_value_nulls
FROM BRONZE.OLIST_ORDER_ITEMS;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(order_id IS NULL) AS order_id_nulls,
    COUNT_IF(payment_sequential IS NULL) AS payment_sequential_nulls,
    COUNT_IF(payment_type IS NULL) AS payment_type_nulls,
    COUNT_IF(payment_installments IS NULL) AS payment_installments_nulls,
    COUNT_IF(payment_value IS NULL) AS payment_value_nulls
FROM BRONZE.OLIST_ORDER_PAYMENTS;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(review_id IS NULL) AS review_id_nulls,
    COUNT_IF(order_id IS NULL) AS order_id_nulls,
    COUNT_IF(review_score IS NULL) AS review_score_nulls,
    COUNT_IF(review_comment_title IS NULL) AS review_comment_title_nulls,
    COUNT_IF(review_comment_message IS NULL) AS review_comment_message_nulls,
    COUNT_IF(review_creation_date IS NULL) AS review_creation_date_nulls,
    COUNT_IF(review_answer_timestamp IS NULL) AS review_answer_timestamp_nulls
FROM BRONZE.OLIST_ORDER_REVIEWS;


SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(product_id IS NULL) AS product_id_nulls,
    COUNT_IF(product_category_name IS NULL) AS product_category_name_nulls,
    COUNT_IF(product_name_lenght IS NULL) AS product_name_lenght_nulls,
    COUNT_IF(product_description_lenght IS NULL) AS product_description_lenght_nulls,
    COUNT_IF(product_photos_qty IS NULL) AS product_photos_qty_nulls,
    COUNT_IF(product_weight_g IS NULL) AS product_weight_g_nulls,
    COUNT_IF(product_length_cm IS NULL) AS product_length_cm_nulls,
    COUNT_IF(product_height_cm IS NULL) AS product_height_cm_nulls,
    COUNT_IF(product_width_cm IS NULL) AS product_width_cm_nulls
FROM BRONZE.OLIST_PRODUCTS; 

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(seller_id IS NULL) AS seller_id_nulls,
    COUNT_IF(seller_zip_code_prefix IS NULL) AS seller_zip_code_prefix_nulls,
    COUNT_IF(seller_city IS NULL) AS seller_city_nulls,
    COUNT_IF(seller_state IS NULL) AS seller_state_nulls
FROM BRONZE.OLIST_SELLERS;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(C1 IS NULL) AS product_category_name_nulls,
    COUNT_IF(C2 IS NULL) AS product_category_name_english_nulls
FROM BRONZE.OLIST_PRODUCT_CATEGORY_NAME;

SELECT
    COUNT_IF(ORDER_APPROVED_AT IS NULL),
    COUNT_IF(ORDER_DELIVERED_CARRIER_DATE IS NULL),
    COUNT_IF(ORDER_DELIVERED_CUSTOMER_DATE IS NULL)
FROM BRONZE.OLIST_ORDERS;

CREATE TABLE IF NOT EXISTS SILVER.ORDER_DATASET_CLEAN AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE
FROM BRONZE.OLIST_ORDERS
WHERE ORDER_APPROVED_AT IS NOT NULL
  AND ORDER_DELIVERED_CARRIER_DATE IS NOT NULL
  AND ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL;

SELECT
    COUNT_IF(ORDER_APPROVED_AT IS NULL) AS approved_at_nulls,
    COUNT_IF(ORDER_DELIVERED_CARRIER_DATE IS NULL) AS carrier_date_nulls,
    COUNT_IF(ORDER_DELIVERED_CUSTOMER_DATE IS NULL) AS customer_date_nulls
FROM SILVER.ORDER_DATASET_CLEAN;


-- Verify the cleaned products table has no NULLs
SELECT
    COUNT_IF(PRODUCT_CATEGORY_NAME IS NULL) AS CATEGORY_NULLS,
    COUNT_IF(PRODUCT_NAME_LENGHT IS NULL) AS NAME_NULLS,
    COUNT_IF(PRODUCT_DESCRIPTION_LENGHT IS NULL) AS DESCRIPTION_NULLS,
    COUNT_IF(PRODUCT_PHOTOS_QTY IS NULL) AS PHOTO_NULLS,
    COUNT_IF(PRODUCT_WEIGHT_G IS NULL) AS WEIGHT_NULLS,
    COUNT_IF(PRODUCT_LENGTH_CM IS NULL) AS LENGTH_NULLS,
    COUNT_IF(PRODUCT_HEIGHT_CM IS NULL) AS HEIGHT_NULLS,
    COUNT_IF(PRODUCT_WIDTH_CM IS NULL) AS WIDTH_NULLS
FROM BRONZE.OLIST_PRODUCTS_CLEANED;

-- Query the product category name translation table
SELECT
    COUNT_IF(REVIEW_ID IS NULL) AS REVIEW_ID_NULLS,
    COUNT_IF(ORDER_ID IS NULL) AS ORDER_ID_NULLS
FROM BRONZE.OLIST_ORDER_REVIEWS;


-- ============================================================
-- SILVER LAYER - Cleaned tables
-- ============================================================

USE DATABASE OLIST_PROJECT;

USE SCHEMA SILVER;

CREATE OR REPLACE TABLE SILVER.CUSTOMERS_CLEANED AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM BRONZE.OLIST_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.PRODUCTS_CLEANED AS
SELECT
    PRODUCT_ID,
    COALESCE(PRODUCT_CATEGORY_NAME, 'Unknown') AS PRODUCT_CATEGORY_NAME,
    COALESCE(PRODUCT_NAME_LENGHT, 0) AS PRODUCT_NAME_LENGHT,
    COALESCE(PRODUCT_DESCRIPTION_LENGHT, 0) AS PRODUCT_DESCRIPTION_LENGHT,
    COALESCE(PRODUCT_PHOTOS_QTY, 0) AS PRODUCT_PHOTOS_QTY,
    COALESCE(PRODUCT_WEIGHT_G, 0) AS PRODUCT_WEIGHT_G,
    COALESCE(PRODUCT_LENGTH_CM, 0) AS PRODUCT_LENGTH_CM,
    COALESCE(PRODUCT_HEIGHT_CM, 0) AS PRODUCT_HEIGHT_CM,
    COALESCE(PRODUCT_WIDTH_CM, 0) AS PRODUCT_WIDTH_CM
FROM BRONZE.OLIST_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.SELLERS_CLEANED AS
SELECT
    SELLER_ID,
    SELLER_ZIP_CODE_PREFIX,
    SELLER_CITY,
    SELLER_STATE
FROM BRONZE.OLIST_SELLERS
WHERE SELLER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.ORDER_PAYMENTS_CLEANED AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM BRONZE.OLIST_ORDER_PAYMENTS
WHERE ORDER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS_CLEANED AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE
FROM BRONZE.OLIST_ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL;

-- ============================================================
-- GOLD LAYER - Dimensional Model
-- ============================================================

CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

-- ============================================================
-- DIM_CUSTOMER
-- ============================================================

CREATE OR REPLACE TABLE DIM_CUSTOMER (
CUSTOMER_SK NUMBER AUTOINCREMENT PRIMARY KEY,
CUSTOMER_ID VARCHAR,
CUSTOMER_UNIQUE_ID VARCHAR,
CUSTOMER_CITY VARCHAR,
CUSTOMER_STATE VARCHAR,
DW_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DW_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO DIM_CUSTOMER (
CUSTOMER_ID,
CUSTOMER_UNIQUE_ID,
CUSTOMER_CITY,
CUSTOMER_STATE
)
SELECT
CUSTOMER_ID,
CUSTOMER_UNIQUE_ID,
CUSTOMER_CITY,
CUSTOMER_STATE
FROM SILVER.CUSTOMERS_CLEANED;

-- SCD TYPE 1

MERGE INTO DIM_CUSTOMER T
USING SILVER.CUSTOMERS_CLEANED S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED AND (
T.CUSTOMER_CITY <> S.CUSTOMER_CITY OR
T.CUSTOMER_STATE <> S.CUSTOMER_STATE
)
THEN UPDATE SET
CUSTOMER_CITY = S.CUSTOMER_CITY,
CUSTOMER_STATE = S.CUSTOMER_STATE,
DW_UPDATED_AT = CURRENT_TIMESTAMP

WHEN NOT MATCHED THEN
INSERT (
CUSTOMER_ID,
CUSTOMER_UNIQUE_ID,
CUSTOMER_CITY,
CUSTOMER_STATE
)
VALUES (
S.CUSTOMER_ID,
S.CUSTOMER_UNIQUE_ID,
S.CUSTOMER_CITY,
S.CUSTOMER_STATE
);

-- ============================================================
-- DIM_PRODUCT
-- ============================================================

CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT
MD5(PRODUCT_ID) AS PRODUCT_SK,
PRODUCT_ID,
PRODUCT_CATEGORY_NAME,
PRODUCT_NAME_LENGHT,
PRODUCT_DESCRIPTION_LENGHT,
PRODUCT_PHOTOS_QTY,
PRODUCT_WEIGHT_G,
PRODUCT_LENGTH_CM,
PRODUCT_HEIGHT_CM,
PRODUCT_WIDTH_CM,
CURRENT_TIMESTAMP AS DW_CREATED_AT
FROM SILVER.PRODUCTS_CLEANED;

-- ============================================================
-- DIM_SELLER
-- ============================================================

CREATE OR REPLACE TABLE DIM_SELLER AS
SELECT
MD5(SELLER_ID) AS SELLER_SK,
SELLER_ID,
SELLER_ZIP_CODE_PREFIX,
SELLER_CITY,
SELLER_STATE,
CURRENT_TIMESTAMP AS DW_CREATED_AT
FROM SILVER.SELLERS_CLEANED;

-- ============================================================
-- DIM_DATE
-- ============================================================

CREATE OR REPLACE TABLE DIM_DATE AS
WITH DATE_SPINE AS (
SELECT DATEADD(DAY, SEQ4(), '2016-01-01') AS DATE_DAY
FROM TABLE(GENERATOR(ROWCOUNT => 2000))
)
SELECT
TO_NUMBER(TO_CHAR(DATE_DAY,'YYYYMMDD')) AS DATE_SK,
DATE_DAY AS FULL_DATE,
YEAR(DATE_DAY) AS YEAR,
QUARTER(DATE_DAY) AS QUARTER,
MONTH(DATE_DAY) AS MONTH,
MONTHNAME(DATE_DAY) AS MONTH_NAME,
WEEKOFYEAR(DATE_DAY) AS WEEK_OF_YEAR,
DAY(DATE_DAY) AS DAY_OF_MONTH,
DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK
FROM DATE_SPINE
WHERE DATE_DAY <= '2020-12-31';

-- ============================================================
-- DIM_PAYMENT
-- ============================================================

CREATE OR REPLACE TABLE DIM_PAYMENT AS
SELECT
MD5(ORDER_ID || '-' || PAYMENT_SEQUENTIAL) AS PAYMENT_SK,
ORDER_ID,
PAYMENT_SEQUENTIAL,
PAYMENT_TYPE,
PAYMENT_INSTALLMENTS,
PAYMENT_VALUE,
CURRENT_TIMESTAMP AS DW_CREATED_AT
FROM SILVER.ORDER_PAYMENTS_CLEANED;

-- ============================================================
-- FACT_ORDER_ITEMS
-- ============================================================

CREATE OR REPLACE TABLE FACT_ORDER_ITEMS AS

SELECT

MD5(OI.ORDER_ID || '-' || OI.ORDER_ITEM_ID) AS ORDER_ITEM_SK,

MD5(OI.PRODUCT_ID) AS PRODUCT_SK,
MD5(OI.SELLER_ID) AS SELLER_SK,

DC.CUSTOMER_SK,

TO_NUMBER(
    TO_CHAR(
        O.ORDER_PURCHASE_TIMESTAMP::DATE,
        'YYYYMMDD'
    )
) AS DATE_SK,

OI.ORDER_ID,
OI.ORDER_ITEM_ID,

O.ORDER_STATUS,

O.ORDER_PURCHASE_TIMESTAMP,
O.ORDER_APPROVED_AT,
O.ORDER_DELIVERED_CARRIER_DATE,
O.ORDER_DELIVERED_CUSTOMER_DATE,
O.ORDER_ESTIMATED_DELIVERY_DATE,

OI.PRICE AS ITEM_PRICE,
OI.FREIGHT_VALUE,

OI.PRICE + OI.FREIGHT_VALUE AS TOTAL_AMOUNT,

DATEDIFF(
    DAY,
    O.ORDER_PURCHASE_TIMESTAMP,
    O.ORDER_DELIVERED_CUSTOMER_DATE
) AS ACTUAL_DELIVERY_DAYS,

CURRENT_TIMESTAMP AS DW_CREATED_AT

FROM SILVER.ORDER_ITEMS_CLEANED OI

JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID

JOIN DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID;

SELECT COUNT(*) 
FROM GOLD.FACT_ORDER_ITEMS;

SELECT *
FROM GOLD.FACT_ORDER_ITEMS
LIMIT 10;

SHOW TABLES IN SCHEMA GOLD;
SELECT COUNT(*) FROM GOLD.FACT_ORDER_ITEMS;



SELECT COUNT(*) FROM GOLD.FACT_ORDER_ITEMS;
SELECT COUNT(*) FROM SILVER.ORDER_ITEMS_CLEANED;

SELECT COUNT(*) FROM SILVER.ORDER_ITEMS_CLEANED;

SELECT COUNT(*) FROM SILVER.ORDER_DATASET_CLEAN;

SELECT COUNT(*) FROM GOLD.DIM_CUSTOMER;

SELECT COUNT(*) FROM GOLD.DIM_PRODUCT;

SELECT COUNT(*) FROM GOLD.DIM_SELLER;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID
JOIN GOLD.DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
LEFT JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID
JOIN GOLD.DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID;


SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN GOLD.DIM_PRODUCT P
ON OI.PRODUCT_ID = P.PRODUCT_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN GOLD.DIM_SELLER S
ON OI.SELLER_ID = S.SELLER_ID;

CREATE OR REPLACE TABLE GOLD.FACT_ORDER_ITEMS AS
SELECT
    MD5(oi.order_id || '-' || CAST(oi.order_item_id AS VARCHAR)) AS order_item_sk,
    MD5(p.product_id) AS product_sk,
    MD5(s.seller_id) AS seller_sk,
    TO_NUMBER(TO_CHAR(o.order_purchase_timestamp::DATE, 'YYYYMMDD')) AS date_sk,
    dc.customer_sk,

    oi.order_id,
    oi.order_item_id,
    o.order_status,

    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_carrier_date,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,

    oi.price AS item_price,
    oi.freight_value,
    oi.price + oi.freight_value AS total_amount,

    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_delivered_customer_date
    ) AS actual_delivery_days,

    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_estimated_delivery_date
    ) AS estimated_delivery_days,

    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_delivered_customer_date
    )
    -
    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_estimated_delivery_date
    ) AS delivery_delay_days,

    CURRENT_TIMESTAMP AS dw_created_at

FROM SILVER.ORDER_ITEMS_CLEANED oi

JOIN SILVER.ORDER_DATASET_CLEAN o
    ON oi.order_id = o.order_id

JOIN SILVER.PRODUCTS_CLEANED p
    ON oi.product_id = p.product_id

JOIN SILVER.SELLERS_CLEANED s
    ON oi.seller_id = s.seller_id

JOIN GOLD.DIM_CUSTOMER dc
    ON o.customer_id = dc.customer_id;

    SELECT COUNT(*)
FROM GOLD.FACT_ORDER_ITEMS;

SELECT
COUNT(*) AS TotalRows,
COUNT(CUSTOMER_SK) AS CustomerSK,
COUNT(PRODUCT_SK) AS ProductSK,
COUNT(SELLER_SK) AS SellerSK,
COUNT(DATE_SK) AS DateSK
FROM GOLD.FACT_ORDER_ITEMS;

SELECT *
FROM GOLD.DIM_CUSTOMER
LIMIT 10;

CREATE DATABASE OLIST_DWH;

CREATE SCHEMA OLIST_DWH.BRONZE;
CREATE SCHEMA OLIST_DWH.SILVER;
CREATE SCHEMA OLIST_DWH.GOLD;

CREATE OR REPLACE TABLE BRONZE.OLIST_CUSTOMERS (
    CUSTOMER_ID STRING,
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_ZIP_CODE_PREFIX NUMBER,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING
);

CREATE OR REPLACE TABLE BRONZE.OLIST_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_STATUS STRING,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVED_AT TIMESTAMP,
    ORDER_DELIVERED_CARRIER_DATE TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE BRONZE.OLIST_ORDER_ITEMS (
    ORDER_ID STRING,
    ORDER_ITEM_ID NUMBER,
    PRODUCT_ID STRING,
    SELLER_ID STRING,
    SHIPPING_LIMIT_DATE TIMESTAMP,
    PRICE FLOAT,
    FREIGHT_VALUE FLOAT
);

CREATE OR REPLACE TABLE BRONZE.OLIST_PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_CATEGORY_NAME STRING,
    PRODUCT_NAME_LENGTH NUMBER,
    PRODUCT_DESCRIPTION_LENGTH NUMBER,
    PRODUCT_PHOTOS_QTY NUMBER,
    PRODUCT_WEIGHT_G NUMBER,
    PRODUCT_LENGTH_CM NUMBER,
    PRODUCT_HEIGHT_CM NUMBER,
    PRODUCT_WIDTH_CM NUMBER
);

CREATE OR REPLACE TABLE BRONZE.OLIST_SELLERS (
    SELLER_ID STRING,
    SELLER_ZIP_CODE_PREFIX NUMBER,
    SELLER_CITY STRING,
    SELLER_STATE STRING
);

CREATE OR REPLACE TABLE BRONZE.OLIST_ORDER_PAYMENTS (
    ORDER_ID STRING,
    PAYMENT_SEQUENTIAL NUMBER,
    PAYMENT_TYPE STRING,
    PAYMENT_INSTALLMENTS NUMBER,
    PAYMENT_VALUE FLOAT
);

CREATE OR REPLACE TABLE BRONZE.OLIST_ORDER_REVIEWS (
    REVIEW_ID STRING,
    ORDER_ID STRING,
    REVIEW_SCORE NUMBER,
    REVIEW_COMMENT_TITLE STRING,
    REVIEW_COMMENT_MESSAGE STRING,
    REVIEW_CREATION_DATE DATE,
    REVIEW_ANSWER_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE BRONZE.OLIST_GEOLOCATION (
    GEOLOCATION_ZIP_CODE_PREFIX NUMBER,
    GEOLOCATION_LAT FLOAT,
    GEOLOCATION_LNG FLOAT,
    GEOLOCATION_CITY STRING,
    GEOLOCATION_STATE STRING
);

CREATE OR REPLACE TABLE BRONZE.OLIST_PRODUCT_CATEGORY_NAME (
    PRODUCT_CATEGORY_NAME STRING,
    PRODUCT_CATEGORY_NAME_ENGLISH STRING
);

COPY INTO BRONZE.OLIST_CUSTOMERS
FROM @BRONZE.OLIST_STAGE/customers.csv
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);

USE DATABASE OLIST_PROJECT;

USE SCHEMA SILVER;

CREATE OR REPLACE TABLE SILVER.CUSTOMERS_CLEANED AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM BRONZE.OLIST_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.PRODUCTS_CLEANED AS
SELECT
    PRODUCT_ID,
    COALESCE(PRODUCT_CATEGORY_NAME, 'Unknown') AS PRODUCT_CATEGORY_NAME,
    COALESCE(PRODUCT_NAME_LENGHT, 0) AS PRODUCT_NAME_LENGHT,
    COALESCE(PRODUCT_DESCRIPTION_LENGHT, 0) AS PRODUCT_DESCRIPTION_LENGHT,
    COALESCE(PRODUCT_PHOTOS_QTY, 0) AS PRODUCT_PHOTOS_QTY,
    COALESCE(PRODUCT_WEIGHT_G, 0) AS PRODUCT_WEIGHT_G,
    COALESCE(PRODUCT_LENGTH_CM, 0) AS PRODUCT_LENGTH_CM,
    COALESCE(PRODUCT_HEIGHT_CM, 0) AS PRODUCT_HEIGHT_CM,
    COALESCE(PRODUCT_WIDTH_CM, 0) AS PRODUCT_WIDTH_CM
FROM BRONZE.OLIST_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.SELLERS_CLEANED AS
SELECT
    SELLER_ID,
    SELLER_ZIP_CODE_PREFIX,
    SELLER_CITY,
    SELLER_STATE
FROM BRONZE.OLIST_SELLERS
WHERE SELLER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.ORDER_PAYMENTS_CLEANED AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM BRONZE.OLIST_ORDER_PAYMENTS
WHERE ORDER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS_CLEANED AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE
FROM BRONZE.OLIST_ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL;

-- GOLD LAYER - Dimensional Model
-- ============================================================

CREATE SCHEMA IF NOT EXISTS GOLD;
USE SCHEMA GOLD;

-- ============================================================
-- DIM_CUSTOMER
-- ============================================================

CREATE OR REPLACE TABLE DIM_CUSTOMER (
CUSTOMER_SK NUMBER AUTOINCREMENT PRIMARY KEY,
CUSTOMER_ID VARCHAR,
CUSTOMER_UNIQUE_ID VARCHAR,
CUSTOMER_CITY VARCHAR,
CUSTOMER_STATE VARCHAR,
DW_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DW_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO DIM_CUSTOMER (
CUSTOMER_ID,
CUSTOMER_UNIQUE_ID,
CUSTOMER_CITY,
CUSTOMER_STATE
)
SELECT
CUSTOMER_ID,
CUSTOMER_UNIQUE_ID,
CUSTOMER_CITY,
CUSTOMER_STATE
FROM SILVER.CUSTOMERS_CLEANED;

-- SCD TYPE 1

MERGE INTO DIM_CUSTOMER T
USING SILVER.CUSTOMERS_CLEANED S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED AND (
T.CUSTOMER_CITY <> S.CUSTOMER_CITY OR
T.CUSTOMER_STATE <> S.CUSTOMER_STATE
)
THEN UPDATE SET
CUSTOMER_CITY = S.CUSTOMER_CITY,
CUSTOMER_STATE = S.CUSTOMER_STATE,
DW_UPDATED_AT = CURRENT_TIMESTAMP

WHEN NOT MATCHED THEN
INSERT (
CUSTOMER_ID,
CUSTOMER_UNIQUE_ID,
CUSTOMER_CITY,
CUSTOMER_STATE
)
VALUES (
S.CUSTOMER_ID,
S.CUSTOMER_UNIQUE_ID,
S.CUSTOMER_CITY,
S.CUSTOMER_STATE
);

-- ============================================================
-- DIM_PRODUCT
-- ============================================================

CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT
MD5(PRODUCT_ID) AS PRODUCT_SK,
PRODUCT_ID,
PRODUCT_CATEGORY_NAME,
PRODUCT_NAME_LENGHT,
PRODUCT_DESCRIPTION_LENGHT,
PRODUCT_PHOTOS_QTY,
PRODUCT_WEIGHT_G,
PRODUCT_LENGTH_CM,
PRODUCT_HEIGHT_CM,
PRODUCT_WIDTH_CM,
CURRENT_TIMESTAMP AS DW_CREATED_AT
FROM SILVER.PRODUCTS_CLEANED;

-- ============================================================
-- DIM_SELLER
-- ============================================================

CREATE OR REPLACE TABLE DIM_SELLER AS
SELECT
MD5(SELLER_ID) AS SELLER_SK,
SELLER_ID,
SELLER_ZIP_CODE_PREFIX,
SELLER_CITY,
SELLER_STATE,
CURRENT_TIMESTAMP AS DW_CREATED_AT
FROM SILVER.SELLERS_CLEANED;

-- ============================================================
-- DIM_DATE
-- ============================================================

CREATE OR REPLACE TABLE DIM_DATE AS
WITH DATE_SPINE AS (
SELECT DATEADD(DAY, SEQ4(), '2016-01-01') AS DATE_DAY
FROM TABLE(GENERATOR(ROWCOUNT => 2000))
)
SELECT
TO_NUMBER(TO_CHAR(DATE_DAY,'YYYYMMDD')) AS DATE_SK,
DATE_DAY AS FULL_DATE,
YEAR(DATE_DAY) AS YEAR,
QUARTER(DATE_DAY) AS QUARTER,
MONTH(DATE_DAY) AS MONTH,
MONTHNAME(DATE_DAY) AS MONTH_NAME,
WEEKOFYEAR(DATE_DAY) AS WEEK_OF_YEAR,
DAY(DATE_DAY) AS DAY_OF_MONTH,
DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK
FROM DATE_SPINE
WHERE DATE_DAY <= '2020-12-31';

-- ============================================================
-- DIM_PAYMENT
-- ============================================================

CREATE OR REPLACE TABLE DIM_PAYMENT AS
SELECT
MD5(ORDER_ID || '-' || PAYMENT_SEQUENTIAL) AS PAYMENT_SK,
ORDER_ID,
PAYMENT_SEQUENTIAL,
PAYMENT_TYPE,
PAYMENT_INSTALLMENTS,
PAYMENT_VALUE,
CURRENT_TIMESTAMP AS DW_CREATED_AT
FROM SILVER.ORDER_PAYMENTS_CLEANED;

-- ============================================================
-- FACT_ORDER_ITEMS
-- ============================================================

CREATE OR REPLACE TABLE FACT_ORDER_ITEMS AS

SELECT

MD5(OI.ORDER_ID || '-' || OI.ORDER_ITEM_ID) AS ORDER_ITEM_SK,

MD5(OI.PRODUCT_ID) AS PRODUCT_SK,
MD5(OI.SELLER_ID) AS SELLER_SK,

DC.CUSTOMER_SK,

TO_NUMBER(
    TO_CHAR(
        O.ORDER_PURCHASE_TIMESTAMP::DATE,
        'YYYYMMDD'
    )
) AS DATE_SK,

OI.ORDER_ID,
OI.ORDER_ITEM_ID,

O.ORDER_STATUS,

O.ORDER_PURCHASE_TIMESTAMP,
O.ORDER_APPROVED_AT,
O.ORDER_DELIVERED_CARRIER_DATE,
O.ORDER_DELIVERED_CUSTOMER_DATE,
O.ORDER_ESTIMATED_DELIVERY_DATE,

OI.PRICE AS ITEM_PRICE,
OI.FREIGHT_VALUE,

OI.PRICE + OI.FREIGHT_VALUE AS TOTAL_AMOUNT,

DATEDIFF(
    DAY,
    O.ORDER_PURCHASE_TIMESTAMP,
    O.ORDER_DELIVERED_CUSTOMER_DATE
) AS ACTUAL_DELIVERY_DAYS,

CURRENT_TIMESTAMP AS DW_CREATED_AT

FROM SILVER.ORDER_ITEMS_CLEANED OI

JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID

JOIN DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID;

SELECT COUNT(*) 
FROM GOLD.FACT_ORDER_ITEMS;

SELECT *
FROM GOLD.FACT_ORDER_ITEMS
LIMIT 10;

SHOW TABLES IN SCHEMA GOLD;
SELECT COUNT(*) FROM GOLD.FACT_ORDER_ITEMS;



SELECT COUNT(*) FROM GOLD.FACT_ORDER_ITEMS;
SELECT COUNT(*) FROM SILVER.ORDER_ITEMS_CLEANED;

SELECT COUNT(*) FROM SILVER.ORDER_ITEMS_CLEANED;

SELECT COUNT(*) FROM SILVER.ORDER_DATASET_CLEAN;

SELECT COUNT(*) FROM GOLD.DIM_CUSTOMER;

SELECT COUNT(*) FROM GOLD.DIM_PRODUCT;

SELECT COUNT(*) FROM GOLD.DIM_SELLER;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID
JOIN GOLD.DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
LEFT JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN SILVER.ORDER_DATASET_CLEAN O
ON OI.ORDER_ID = O.ORDER_ID
JOIN GOLD.DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID;


SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN GOLD.DIM_PRODUCT P
ON OI.PRODUCT_ID = P.PRODUCT_ID;

SELECT COUNT(*)
FROM SILVER.ORDER_ITEMS_CLEANED OI
JOIN GOLD.DIM_SELLER S
ON OI.SELLER_ID = S.SELLER_ID;

CREATE OR REPLACE TABLE GOLD.FACT_ORDER_ITEMS AS
SELECT
    MD5(oi.order_id || '-' || CAST(oi.order_item_id AS VARCHAR)) AS order_item_sk,
    MD5(p.product_id) AS product_sk,
    MD5(s.seller_id) AS seller_sk,
    TO_NUMBER(TO_CHAR(o.order_purchase_timestamp::DATE, 'YYYYMMDD')) AS date_sk,
    dc.customer_sk,

    oi.order_id,
    oi.order_item_id,
    o.order_status,

    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_carrier_date,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,

    oi.price AS item_price,
    oi.freight_value,
    oi.price + oi.freight_value AS total_amount,

    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_delivered_customer_date
    ) AS actual_delivery_days,

    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_estimated_delivery_date
    ) AS estimated_delivery_days,

    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_delivered_customer_date
    )
    -
    DATEDIFF(
        'day',
        o.order_purchase_timestamp,
        o.order_estimated_delivery_date
    ) AS delivery_delay_days,

    CURRENT_TIMESTAMP AS dw_created_at

FROM SILVER.ORDER_ITEMS_CLEANED oi

JOIN SILVER.ORDER_DATASET_CLEAN o
    ON oi.order_id = o.order_id

JOIN SILVER.PRODUCTS_CLEANED p
    ON oi.product_id = p.product_id

JOIN SILVER.SELLERS_CLEANED s
    ON oi.seller_id = s.seller_id

JOIN GOLD.DIM_CUSTOMER dc
    ON o.customer_id = dc.customer_id;

    SELECT COUNT(*)
FROM GOLD.FACT_ORDER_ITEMS;

SELECT
COUNT(*) AS TotalRows,
COUNT(CUSTOMER_SK) AS CustomerSK,
COUNT(PRODUCT_SK) AS ProductSK,
COUNT(SELLER_SK) AS SellerSK,
COUNT(DATE_SK) AS DateSK
FROM GOLD.FACT_ORDER_ITEMS;

SELECT *
FROM GOLD.DIM_CUSTOMER
LIMIT 10;

SELECT COUNT(*) FROM BRONZE.OLIST_CUSTOMERS;
SELECT COUNT(*) FROM SILVER.CUSTOMERS_CLEANED;
SELECT COUNT(*) FROM GOLD.DIM_CUSTOMER;

SELECT COUNT(*) FROM GOLD.FACT_ORDER_ITEMS;

CREATE OR REPLACE TASK ETL_PIPELINE
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 6 * * * UTC'
AS

CALL LOAD_OLIST_DATA();

ALTER TASK ETL_PIPELINE RESUME;

SHOW TASKS;

ALTER TASK ETL_PIPELINE RESUME;
SHOW TASKS;

EXECUTE TASK ETL_PIPELINE;

SHOW TASKS;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC;

SELECT COUNT(*) FROM BRONZE.OLIST_CUSTOMERS;
SELECT COUNT(*) FROM SILVER.CUSTOMERS_CLEANED;
SELECT COUNT(*) FROM GOLD.DIM_CUSTOMER;
SELECT COUNT(*) FROM GOLD.DIM_PRODUCT;
SELECT COUNT(*) FROM GOLD.FACT_ORDER_ITEMS;

ALTER TASK ETL_PIPELINE RESUME;

CREATE NOTIFICATION INTEGRATION email_int
TYPE = EMAIL
ENABLED = TRUE;

CALL SYSTEM$SEND_EMAIL(
    'EMAIL_INT',
    'vaishnavipm025@gmail.com',
    'ETL Pipeline Status',
    'ETL Pipeline executed successfully.'
);

SELECT CURRENT_ROLE();

SHOW NOTIFICATION INTEGRATIONS;

CALL SYSTEM$SEND_EMAIL(
    'EMAIL_INT',
    'vaishnavipm025@gmail.com',
    'ETL Pipeline Test',
    'This is a test email from Snowflake.'
);

CALL SYSTEM$SEND_EMAIL(
    'EMAIL_INT',
    'vaishnavipm025@gmail.com',
    'ETL Pipeline Status',
    'The ETL pipeline completed successfully.'
);

SHOW NOTIFICATION INTEGRATIONS;

CREATE OR REPLACE ALERT ETL_FAILURE_ALERT
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
IF (
    EXISTS (
        SELECT 1
        FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
        WHERE STATE = 'FAILED'
          AND SCHEDULED_TIME > DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
    )
)
THEN
CALL SYSTEM$SEND_EMAIL(
    'email_int',
    'vaishnavipm025@gmail.com',
    'ETL Pipeline Failed',
    'One of the ETL tasks has failed.'
);